name: Generate Customized GitHub Snake Game

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 1-31/3 * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Git identity
        run: |
          git config user.name "David Suter"
          git config user.email "david.raul.suter@icloud.com"

      - name: Generate GitHub Contribution Snake Game
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake-light.svg?color_snake=#7507eb&color_dots=#ffffff,#f7d6e0,#f0aebd,#ea85aa,#e45c97&palette=github-light
            dist/github-snake-dark.svg?color_snake=#cfabf5&color_dots=#3d3347,#f7d6e0,#f0aebd,#ea85aa,#e45c97&palette=github-dark

      - name: Commit and push generated SVG
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add .
          git commit -m "Add generated snake game" -a || echo "No changes to commit"
          git push --set-upstream https://github.com/d-suter/d-suter.git main
