name: Generate Customized GitHub Snake Game

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up Git identity
      run: |
        git config user.name "GitHub Action"
        git config user.email "action@github.com"

    - name: Generate GitHub Contribution Snake Game
      uses: Platane/snk@v3
      with:
        github_user_name: ${{ github.repository_owner }}
        outputs: |
          dist/github-snake.svg?color_snake=%23ebc3c8&color_dots=%23ffffff,%23f7d6e0,%23f0aebd,%23ea85aa,%23e45c97

    - name: Commit and push generated SVG
      run: |
        git add .
        git commit -m "Add generated snake game" -a || echo "No changes to commit"
        git push --set-upstream origin main
      env:
        GITHUB_TOKEN: ${{ secrets.MY_PERSONAL_TOKEN }}
